# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# based on pre-commit
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/Tfloow/Q4_EPL
    rev: v1.2.0
    hooks:
    -   id: some-id